version: "3.8"

services:
  api:
    build: .
    container_name: realestate-api-prod
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
    ports:
      - "${API_PORT:-3000}:3000"
    command: npm run start:prod

volumes:
  db_data:
